name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: ${{ secrets.SERVERPOD_PASSWORD_database }}
      SERVERPOD_PASSWORD_redis: ${{ secrets.SERVERPOD_PASSWORD_redis }}

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'
          dart-version:    '3.10.7'

      - name: Start containers
        working-directory: ai_logb_server 
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: ai_logb_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: ai_logb_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: ai_logb_server
        run: serverpod generate

      - name: Run tests
        working-directory: ai_logb_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: ai_logb_server
        run: docker compose down -v
